- hosts: 127.0.0.1
  vars_files:
    - vars/variables.yaml
  tasks:
    - name: Creating nginx.conf
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/conf.d/nginx_ansible.conf

    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted
